name: RedstoneJukeboxTrig
main: me.cheddar262.RedstoneJukeboxTrig.RedstoneJukeboxTrig
author: cheddar262
description: This plugin causes a jukebox to play whenever a redstone wire powers it.
version: 0.1.1